//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3344
        ///8938
        ///7923
        ///3979
        ///2753
        ///5730
        ///4225
        ///
        ///24216
        ///7432
        ///18284
        ///
        ///3475
        ///9177
        ///6769
        ///11335
        ///8061
        ///9302
        ///8132
        ///
        ///25796
        ///
        ///20937
        ///
        ///2039
        ///4989
        ///5932
        ///5434
        ///5088
        ///7185
        ///1271
        ///8359
        ///5489
        ///8646
        ///
        ///7796
        ///1233
        ///3529
        ///4118
        ///7093
        ///7090
        ///8757
        ///2283
        ///5562
        ///3789
        ///
        ///2296
        ///2105
        ///1978
        ///2981
        ///5682
        ///1627
        ///2285
        ///5654
        ///5596
        ///2022
        ///2733
        ///3078
        ///3176
        ///4158
        ///
        ///6294
        ///3789
        ///1863
        ///5121
        ///6122
        ///7309
        ///7063
        ///4233
        ///1717
        ///6755
        ///5505
        ///2713
        ///
        ///4988
        ///5133
        ///4933
        ///6407
        ///2897
        ///2682
        ///5328
        ///4268
        ///1518
        ///4631
        ///2736
        ///1432
        ///3812
        ///1031
        ///
        ///4553
        ///1109
        ///7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string calorie_list {
            get {
                return ResourceManager.GetString("calorie_list", resourceCulture);
            }
        }
    }
}
